### ISSUE TITLE
Logs like response for the run

### ISSUE THREAD

**Issue by gianarb** [gianarb/gourmet#20]
When you run 

```
POST /func/<id>
```

Right now the idea is return a logs related the function runned in order to understand how it worked.

Status code 200 is the exit code is 0, 500 for all other status code.

**Comment by fntlnz** [comment]
@gianarb In which format are the logs stored?

**Comment by gianarb** [comment]
Right now my idea is stay without storage..

Grab logs from the function and print it into the body with `Content-Type:text/plain`

Is it good to start in your opinion?

The second step could be use multipart to create an http stream.

**Comment by fntlnz** [comment]
🎉
