### ISSUE TITLE
Build a logger

### ISSUE THREAD

**Issue by gianarb** [gianarb/gourmet#4]
Split docker output logger from application logger.

**Comment by fntlnz** [comment]
Yeah and also [this](https://github.com/gianarb/gourmet/blob/master/logger/console.go#L9) should use `log` instead. fmt is not good for logging, it's not safe for concurrency and doesn't have log specific features. fmt is just for formatting.

https://golang.org/pkg/log/

**Comment by gianarb** [comment]
:+1:
